import {
  type AddMemberRequest,
  type RemoveMemberRequest,
  createActor,
} from "@/backend";
import type {
  ConversationPublic,
  GetMessagesRequest,
  MessagePublic,
  MessageType,
  SendMessageRequest,
} from "@/backend";
import { useActor } from "@caffeineai/core-infrastructure";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect } from "react";

// ---------------------------------------------------------------------------
// localStorage helpers for "Delete for me" hidden conversation IDs
// ---------------------------------------------------------------------------
const HIDDEN_CONVS_KEY = "cs_hidden_convs";

function getHiddenConvIds(): Set<string> {
  try {
    const raw = localStorage.getItem(HIDDEN_CONVS_KEY);
    if (!raw) return new Set();
    const arr = JSON.parse(raw) as string[];
    return new Set(arr);
  } catch {
    return new Set();
  }
}

function addHiddenConvId(convIdStr: string): void {
  try {
    const current = getHiddenConvIds();
    current.add(convIdStr);
    localStorage.setItem(HIDDEN_CONVS_KEY, JSON.stringify([...current]));
  } catch {
    // localStorage unavailable — deletion will still clear the in-memory cache
  }
}
function removeHiddenConvId(convIdStr: string): void {
  try {
    const current = getHiddenConvIds();
    if (!current.has(convIdStr)) return;
    current.delete(convIdStr);
    localStorage.setItem(HIDDEN_CONVS_KEY, JSON.stringify([...current]));
  } catch {
    // localStorage unavailable — no-op
  }
}

export function useConversations() {
  const { actor, isFetching } = useActor(createActor);
  return useQuery<ConversationPublic[]>({
    queryKey: ["conversations"],
    queryFn: async () => {
      if (!actor) return [];
      const all = await actor.listConversations();
      // Filter out locally-hidden conversations ("Delete for me" only)
      const hidden = getHiddenConvIds();
      if (hidden.size === 0) return all;
      return all.filter((c) => !hidden.has(c.id.toString()));
    },
    enabled: !!actor && !isFetching,
    staleTime: 0,
    gcTime: 300_000,
    refetchInterval: 5_000,
    refetchIntervalInBackground: false,
    refetchOnWindowFocus: true,
  });
}

export function useConversation(id: bigint | null) {
  const { actor, isFetching } = useActor(createActor);
  return useQuery<ConversationPublic | null>({
    queryKey: ["conversation", id?.toString()],
    queryFn: async () => {
      if (!actor || id === null) return null;
      return actor.getConversation(id);
    },
    enabled: !!actor && !isFetching && id !== null,
    staleTime: 60_000,
    gcTime: 300_000,
    refetchInterval: 30_000,
    refetchIntervalInBackground: false,
    refetchOnWindowFocus: false,
  });
}

export function useMessages(conversationId: bigint | null, limit = 50n) {
  const { actor, isFetching } = useActor(createActor);
  const queryClient = useQueryClient();
  const query = useQuery<MessagePublic[]>({
    queryKey: ["messages", conversationId?.toString()],
    queryFn: async () => {
      if (!actor || conversationId === null) return [];
      const req: GetMessagesRequest = {
        conversationId,
        limit,
        beforeMessageId: undefined,
      };
      const result = await actor.getMessages(req);
      if (result.__kind__ === "ok") return result.ok;
      return [];
    },
    enabled: !!actor && !isFetching && conversationId !== null,
    staleTime: 10_000,
    gcTime: 300_000,
    refetchInterval: 10_000,
    refetchIntervalInBackground: false,
    refetchOnWindowFocus: false,
  });

  // Auto-unhide: if a new message arrives in a hidden conversation, restore it
  // to the conversation list so the user can see the incoming message.
  useEffect(() => {
    if (conversationId === null || !query.data || query.data.length === 0)
      return;
    const convIdStr = conversationId.toString();
    const hidden = getHiddenConvIds();
    if (!hidden.has(convIdStr)) return;
    console.log(
      `[ChatUnhide] Auto-unhiding convId=${convIdStr} because a new message arrived`,
    );
    removeHiddenConvId(convIdStr);
    queryClient.invalidateQueries({ queryKey: ["conversations"] });
  }, [conversationId, query.data, queryClient]);

  return query;
}

export function useSendMessage() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (
      req: SendMessageRequest & { priority?: "normal" | "high" },
    ) => {
      if (!actor) throw new Error("Not connected");
      // Pass priority and ttlSeconds as raw values — the autogenerated serializer
      // in backend.ts handles wrapping them into Candid opt encoding.
      const result = await actor.sendMessage(req);
      if (result.__kind__ === "err") throw new Error(result.err);
      return result.ok;
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({
        queryKey: ["messages", vars.conversationId.toString()],
      });
      queryClient.invalidateQueries({ queryKey: ["conversations"] });
    },
  });
}

export function useMarkRead() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (messageId: bigint) => {
      if (!actor) throw new Error("Not connected");
      return actor.markMessageRead(messageId);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["messages"] });
      queryClient.invalidateQueries({ queryKey: ["conversations"] });
    },
  });
}

export function useAddConversationMember() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (req: AddMemberRequest) => {
      if (!actor) throw new Error("Not connected");
      const result = await actor.addConversationMember(req);
      if (result.__kind__ === "err") throw new Error(result.err);
      return result.ok;
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({
        queryKey: ["conversation", vars.conversationId.toString()],
      });
      queryClient.invalidateQueries({ queryKey: ["conversations"] });
    },
  });
}

export function useRemoveConversationMember() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (req: RemoveMemberRequest) => {
      if (!actor) throw new Error("Not connected");
      const result = await actor.removeConversationMember(req);
      if (result.__kind__ === "err") throw new Error(result.err);
      return result.ok;
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({
        queryKey: ["conversation", vars.conversationId.toString()],
      });
      queryClient.invalidateQueries({ queryKey: ["conversations"] });
    },
  });
}
export type { ConversationPublic, MessagePublic, MessageType };

/** Delete any conversation — group (creator only) or direct (any member). */
/** Delete chat for the current user only — does NOT touch the backend. */
export function useDeleteConversation() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (conversationId: bigint) => {
      const convIdStr = conversationId.toString();
      addHiddenConvId(convIdStr);
      console.log(
        `[ChatDelete] User deleted chat locally only - convId=${convIdStr} (other user still has full history)`,
      );
    },
    onSuccess: (_, conversationId) => {
      queryClient.removeQueries({
        queryKey: ["conversation", conversationId.toString()],
      });
      queryClient.removeQueries({
        queryKey: ["messages", conversationId.toString()],
      });
      queryClient.invalidateQueries({ queryKey: ["conversations"] });
    },
  });
}

/** @deprecated Use useDeleteConversation — works for both group and direct. */
export function useDeleteGroupConversation() {
  return useDeleteConversation();
}
