import {
  type AddMemberRequest,
  type RemoveMemberRequest,
  createActor,
} from "@/backend";
import type {
  ConversationPublic,
  GetMessagesRequest,
  MessagePublic,
  MessageType,
  SendMessageRequest,
} from "@/backend";
import { useActor } from "@caffeineai/core-infrastructure";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

export function useConversations() {
  const { actor, isFetching } = useActor(createActor);
  return useQuery<ConversationPublic[]>({
    queryKey: ["conversations"],
    queryFn: async () => {
      if (!actor) return [];
      return actor.listConversations();
    },
    enabled: !!actor && !isFetching,
    staleTime: 10_000,
    refetchInterval: 15_000,
    refetchIntervalInBackground: false,
    refetchOnWindowFocus: false,
  });
}

export function useConversation(id: bigint | null) {
  const { actor, isFetching } = useActor(createActor);
  return useQuery<ConversationPublic | null>({
    queryKey: ["conversation", id?.toString()],
    queryFn: async () => {
      if (!actor || id === null) return null;
      return actor.getConversation(id);
    },
    enabled: !!actor && !isFetching && id !== null,
    staleTime: 10_000,
    refetchInterval: 15_000,
    refetchIntervalInBackground: false,
    refetchOnWindowFocus: false,
  });
}

export function useMessages(conversationId: bigint | null, limit = 50n) {
  const { actor, isFetching } = useActor(createActor);
  return useQuery<MessagePublic[]>({
    queryKey: ["messages", conversationId?.toString()],
    queryFn: async () => {
      if (!actor || conversationId === null) return [];
      const req: GetMessagesRequest = {
        conversationId,
        limit,
        beforeMessageId: undefined,
      };
      const result = await actor.getMessages(req);
      if (result.__kind__ === "ok") return result.ok;
      return [];
    },
    enabled: !!actor && !isFetching && conversationId !== null,
    staleTime: 3_000,
    refetchInterval: 6_000,
    refetchIntervalInBackground: false,
    refetchOnWindowFocus: false,
  });
}

export function useSendMessage() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (
      req: SendMessageRequest & { priority?: "normal" | "high" },
    ) => {
      if (!actor) throw new Error("Not connected");
      // Pass priority and ttlSeconds as raw values — the autogenerated serializer
      // in backend.ts handles wrapping them into Candid opt encoding.
      const result = await actor.sendMessage(req);
      if (result.__kind__ === "err") throw new Error(result.err);
      return result.ok;
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({
        queryKey: ["messages", vars.conversationId.toString()],
      });
      queryClient.invalidateQueries({ queryKey: ["conversations"] });
    },
  });
}

export function useMarkRead() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (messageId: bigint) => {
      if (!actor) throw new Error("Not connected");
      return actor.markMessageRead(messageId);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["messages"] });
    },
  });
}

export function useAddConversationMember() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (req: AddMemberRequest) => {
      if (!actor) throw new Error("Not connected");
      const result = await actor.addConversationMember(req);
      if (result.__kind__ === "err") throw new Error(result.err);
      return result.ok;
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({
        queryKey: ["conversation", vars.conversationId.toString()],
      });
      queryClient.invalidateQueries({ queryKey: ["conversations"] });
    },
  });
}

export function useRemoveConversationMember() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (req: RemoveMemberRequest) => {
      if (!actor) throw new Error("Not connected");
      const result = await actor.removeConversationMember(req);
      if (result.__kind__ === "err") throw new Error(result.err);
      return result.ok;
    },
    onSuccess: (_, vars) => {
      queryClient.invalidateQueries({
        queryKey: ["conversation", vars.conversationId.toString()],
      });
      queryClient.invalidateQueries({ queryKey: ["conversations"] });
    },
  });
}
export type { ConversationPublic, MessagePublic, MessageType };
// TODO: remove cast once backend.d.ts + bindgen include deleteGroupConversation
type DeleteResult =
  | { __kind__: "ok"; ok: null }
  | { __kind__: "err"; err: string };
type ActorWithDelete = Record<string, unknown> & {
  deleteGroupConversation?: (id: bigint) => Promise<DeleteResult>;
};

export function useDeleteGroupConversation() {
  const { actor } = useActor(createActor);
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (conversationId: bigint) => {
      if (!actor) throw new Error("Not connected");
      // TODO: remove cast once backend type includes deleteGroupConversation
      const a = actor as unknown as ActorWithDelete;
      if (!a.deleteGroupConversation)
        throw new Error(
          "deleteGroupConversation not yet available in this canister version",
        );
      const result = await a.deleteGroupConversation(conversationId);
      if (result.__kind__ === "err") throw new Error(result.err);
      return result.ok;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["conversations"] });
    },
  });
}
