import {
  MessagePriority as BackendMessagePriority,
  createActor,
} from "@/backend";
import type { MessageType } from "@/backend";
import { useAuth } from "@/context/auth-context";
import {
  clearDeliveredMessages,
  enqueuePendingMessage,
  getAllQueuedMessages,
  getFailedMessages,
  getPendingMessages,
  markDelivered,
  markFailed,
  removePendingMessage,
  updatePendingMessage,
} from "@/lib/offline-queue";
import type { MessagePriority, PendingMessage } from "@/lib/offline-queue";
import { AuditEventType } from "@/types/audit";
import { useActor } from "@caffeineai/core-infrastructure";
import { useCallback, useEffect, useState } from "react";

export type { MessagePriority, PendingMessage };

interface QueueMessage {
  conversationId: string;
  encryptedContent: Uint8Array;
  messageType: string;
  ttlSeconds?: number;
  priority: MessagePriority;
}

export interface UseOfflineQueueResult {
  pendingMessages: PendingMessage[];
  queueMessage: (msg: QueueMessage) => Promise<PendingMessage>;
  retryMessage: (id: string) => Promise<void>;
  deleteQueuedMessage: (id: string) => Promise<void>;
  drainQueue: () => Promise<void>;
  queueDepth: number;
}

export function useOfflineQueue(): UseOfflineQueueResult {
  const { actor } = useActor(createActor);
  const { principal, isAuthenticated } = useAuth();
  const [pendingMessages, setPendingMessages] = useState<PendingMessage[]>([]);

  const refreshQueue = useCallback(async () => {
    const all = await getAllQueuedMessages();
    setPendingMessages(all);
  }, []);

  useEffect(() => {
    refreshQueue();
  }, [refreshQueue]);

  const queueMessage = useCallback(
    async (msg: QueueMessage): Promise<PendingMessage> => {
      const entry = await enqueuePendingMessage(msg);
      await refreshQueue();
      return entry;
    },
    [refreshQueue],
  );

  const drainQueue = useCallback(async () => {
    if (!actor || !isAuthenticated) return;

    const pending = await getPendingMessages();
    if (pending.length === 0) return;

    let drainedCount = 0;

    for (const msg of pending) {
      // Mark as sending
      await updatePendingMessage(msg.id, { status: "sending" });
      await refreshQueue();

      try {
        // Pass priority and ttlSeconds as raw values — the autogenerated
        // backend.ts serializer handles wrapping them into Candid opt encoding.
        const result = await actor.sendMessage({
          conversationId: BigInt(msg.conversationId),
          encryptedContent: msg.encryptedContent,
          messageType: msg.messageType as MessageType,
          ttlSeconds: msg.ttlSeconds ? BigInt(msg.ttlSeconds) : undefined,
          priority:
            msg.priority === "high"
              ? BackendMessagePriority.high
              : msg.priority === "normal"
                ? BackendMessagePriority.normal
                : undefined,
        });

        if (result.__kind__ === "err") {
          throw new Error(result.err ?? "Send failed");
        }

        await markDelivered(msg.id);
        drainedCount++;
      } catch (err) {
        const reason = err instanceof Error ? err.message : "Unknown error";
        await markFailed(msg.id, reason);
      }
    }

    await clearDeliveredMessages();
    await refreshQueue();

    // Fire audit event when queue fully drained
    if (drainedCount > 0 && principal) {
      try {
        await (
          actor as unknown as {
            logAuditEvent: (
              t: { [key: string]: null },
              d: string,
              u: [] | [string],
            ) => Promise<void>;
          }
        ).logAuditEvent(
          { [AuditEventType.messageQueueDrained]: null },
          `Queue drained: ${drainedCount} message(s) delivered`,
          [],
        );
      } catch {
        /* best effort */
      }
    }
  }, [actor, isAuthenticated, principal, refreshQueue]);

  const retryMessage = useCallback(
    async (id: string) => {
      await updatePendingMessage(id, {
        status: "pending",
        errorReason: undefined,
      });
      await refreshQueue();
    },
    [refreshQueue],
  );

  const deleteQueuedMessage = useCallback(
    async (id: string) => {
      await removePendingMessage(id);
      await refreshQueue();
    },
    [refreshQueue],
  );

  // Periodic refresh
  useEffect(() => {
    const interval = setInterval(refreshQueue, 3000);
    return () => clearInterval(interval);
  }, [refreshQueue]);

  return {
    pendingMessages,
    queueMessage,
    retryMessage,
    deleteQueuedMessage,
    drainQueue,
    queueDepth: pendingMessages.filter(
      (m) => m.status === "pending" || m.status === "sending",
    ).length,
  };
}

export { getFailedMessages };
