/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddDeviceRequest {
  'publicKey' : Uint8Array,
  'deviceLabel' : string,
  'deviceId' : string,
}
export interface AddMemberRequest {
  'member' : UserId,
  'conversationId' : ConversationId,
}
export interface Attachment {
  'id' : AttachmentId,
  'messageId' : MessageId,
  'mimeType' : string,
  'encryptedSizeBytes' : bigint,
  'storageKey' : string,
  'uploader' : UserId,
  'uploadedAt' : Timestamp,
}
export type AttachmentId = bigint;
export interface AuditEvent {
  'id' : bigint,
  'orgId' : [] | [OrgId],
  'targetPrincipal' : [] | [UserId],
  'encryptedDetails' : [] | [Uint8Array],
  'timestamp' : Timestamp,
  'actorPrincipal' : UserId,
  'eventType' : AuditEventType,
}
export type AuditEventType = { 'legalHoldRemoved' : null } |
  { 'memberSuspended' : null } |
  { 'userInvited' : null } |
  { 'retentionEnabled' : null } |
  { 'memberAdded' : null } |
  { 'policyExpiryCheckPerformed' : null } |
  { 'retentionPolicyUpdated' : null } |
  { 'retentionDisabled' : null } |
  { 'groupMemberRemoved' : null } |
  { 'orgCreated' : null } |
  { 'orgDeleted' : null } |
  { 'platformSettingsUpdated' : null } |
  { 'escrowAccessGranted' : null } |
  { 'callInitiated' : null } |
  { 'sovereignConfigUpdated' : null } |
  { 'keyRecoveryApproved' : null } |
  { 'keyRecoveryInitiated' : null } |
  { 'messageQueueDrained' : null } |
  { 'memberReactivated' : null } |
  { 'legalHoldPlaced' : null } |
  { 'keyRecoveryCompleted' : null } |
  { 'keyRecoveryRejected' : null } |
  { 'adminAction' : null } |
  { 'orgSettingsUpdated' : null } |
  { 'auditLogExported' : null } |
  { 'escrowEnrolled' : null } |
  { 'messageSent' : null } |
  { 'escrowRevoked' : null } |
  { 'compartmentAssigned' : null } |
  { 'policyReportExported' : null } |
  { 'userRegistered' : null } |
  { 'memberRemoved' : null } |
  { 'retentionPolicyCreated' : null } |
  { 'orgSuspended' : null } |
  { 'userRemoved' : null } |
  { 'priorityMessageSent' : null } |
  { 'orgUpdated' : null } |
  { 'keyEscrowEnrolled' : null } |
  { 'memberRoleChanged' : null };
export type AuditExportEventType = { 'memberSuspended' : null } |
  { 'userInvited' : null } |
  { 'retentionEnabled' : null } |
  { 'memberAdded' : null } |
  { 'retentionDisabled' : null } |
  { 'groupMemberRemoved' : null } |
  { 'orgCreated' : null } |
  { 'escrowAccessGranted' : null } |
  { 'callInitiated' : null } |
  { 'keyRecoveryApproved' : null } |
  { 'keyRecoveryInitiated' : null } |
  { 'keyRecoveryCompleted' : null } |
  { 'keyRecoveryRejected' : null } |
  { 'adminAction' : null } |
  { 'auditLogExported' : null } |
  { 'escrowEnrolled' : null } |
  { 'messageSent' : null } |
  { 'escrowRevoked' : null } |
  { 'userRegistered' : null } |
  { 'memberRemoved' : null } |
  { 'orgSuspended' : null } |
  { 'userRemoved' : null } |
  { 'keyEscrowEnrolled' : null } |
  { 'memberRoleChanged' : null };
export type AuditExportFormat = { 'csv' : null } |
  { 'json' : null };
export interface AuditExportRequest {
  'endDate' : [] | [Timestamp],
  'affectedUser' : [] | [UserId],
  'eventTypes' : [] | [Array<AuditExportEventType>],
  'startDate' : [] | [Timestamp],
  'format' : AuditExportFormat,
}
export type CompartmentLabel = { 'classified' : null } |
  { 'unclassified' : null };
export interface ConfigExportBundle {
  'compartmentMappings' : Array<[ConversationId, CompartmentLabel]>,
  'adminPrincipals' : Array<UserId>,
  'exportedAt' : Timestamp,
  'exportedBy' : UserId,
  'subnetPrincipal' : [] | [string],
  'canisters' : string,
  'groupRetentionPolicies' : Array<[ConversationId, GroupRetentionPolicy]>,
  'residencyLabel' : DataResidency,
}
export type ConversationId = bigint;
export type ConversationKind = { 'group' : null } |
  { 'direct' : null };
export interface ConversationPublic {
  'id' : ConversationId,
  'members' : Array<UserId>,
  'lastMessageAt' : Timestamp,
  'displayName' : [] | [string],
  'kind' : ConversationKind,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : [] | [string],
  'category' : [] | [string],
  'discoverable' : boolean,
  'encryptedName' : [] | [Uint8Array],
}
export interface CreateDirectRequest { 'peer' : UserId }
export interface CreateGroupRequest {
  'initialMembers' : Array<UserId>,
  'displayName' : [] | [string],
  'description' : [] | [string],
  'category' : [] | [string],
  'discoverable' : boolean,
  'encryptedName' : Uint8Array,
}
export interface CreateOrgRequest { 'name' : string, 'description' : string }
export interface CreateRetentionPolicyRequest {
  'orgId' : [] | [OrgId],
  'period' : RetentionPeriod,
  'legalHold' : boolean,
  'autoDelete' : boolean,
}
export type DataExportPermission = { 'orgAdminsOnly' : null } |
  { 'disabled' : null } |
  { 'allMembers' : null };
export type DataResidency = { 'eu' : null } |
  { 'us' : null } |
  { 'apac' : null } |
  { 'global' : null };
export type DenialReason = string;
export interface DeviceRecordPublic {
  'publicKey' : Uint8Array,
  'deviceLabel' : string,
  'deviceId' : string,
  'registeredAt' : Timestamp,
  'lastSeen' : Timestamp,
}
export type EcdhPublicKey = Uint8Array;
export type Error = { 'forbidden' : null } |
  { 'alreadyExists' : null } |
  { 'invalidInput' : null } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export interface EscrowAccessGrant {
  'grantTimestamp' : Timestamp,
  'grantId' : bigint,
  'accessOutcome' : string,
  'targetDeviceId' : string,
  'reason' : string,
  'requestingAdmin' : UserId,
  'targetUserId' : UserId,
}
export interface EscrowRecord {
  'devicePublicKeyFingerprint' : string,
  'userId' : UserId,
  'consentTimestamp' : Timestamp,
  'deviceLabel' : string,
  'wrappedKey' : Uint8Array,
  'deviceId' : string,
  'consentLanguageVersion' : string,
  'revokedAt' : [] | [Timestamp],
  'revokedReason' : [] | [string],
}
export interface EscrowStatsRecord {
  'pendingRecoveries' : bigint,
  'lastRecoveryTimestamp' : [] | [Timestamp],
  'totalEscrowed' : bigint,
}
export type EscrowStatus = { 'active' : null } |
  { 'revoked' : null } |
  { 'recovered' : null } |
  { 'pendingRecovery' : null };
export interface EscrowedUserRecord {
  'orgId' : [] | [OrgId],
  'deviceCount' : bigint,
  'userId' : UserId,
  'escrowStatus' : EscrowStatus,
  'lastBackedUp' : [] | [Timestamp],
}
export interface ExportAuditLogsRequest {
  'afterTimestamp' : [] | [Timestamp],
  'filterEventType' : [] | [AuditEventType],
  'beforeTimestamp' : [] | [Timestamp],
  'filterActor' : [] | [UserId],
  'filterOrgId' : [] | [OrgId],
}
export interface GetAllGroupsRequest { 'orgId' : [] | [OrgId] }
export interface GetAuditLogRequest {
  'afterTimestamp' : [] | [Timestamp],
  'limit' : bigint,
  'filterEventType' : [] | [AuditEventType],
  'beforeTimestamp' : [] | [Timestamp],
  'filterActor' : [] | [UserId],
  'filterOrgId' : [] | [OrgId],
  'afterEventId' : [] | [bigint],
}
export interface GetEscrowedUsersRequest {
  'orgId' : [] | [OrgId],
  'limit' : bigint,
  'afterUserId' : [] | [string],
}
export interface GetGroupMembersRequest { 'groupId' : ConversationId }
export interface GetMessagesRequest {
  'beforeMessageId' : [] | [MessageId],
  'limit' : bigint,
  'conversationId' : ConversationId,
}
export interface GetOrgUsersRequest {
  'orgId' : [] | [OrgId],
  'search' : [] | [string],
  'limit' : bigint,
  'afterUserId' : [] | [UserId],
}
export interface GetOrgUsersResponse {
  'total' : bigint,
  'hasMore' : boolean,
  'members' : Array<OrgMembership>,
}
export interface GetOrgsRequest {
  'search' : [] | [string],
  'limit' : bigint,
  'afterOrgId' : [] | [OrgId],
}
export interface GetOrgsResponse { 'total' : bigint, 'orgs' : Array<OrgRecord> }
export interface GetRetentionMetadataRequest {
  'endDate' : [] | [Timestamp],
  'limit' : bigint,
  'afterMessageId' : [] | [MessageId],
  'convId' : [] | [ConversationId],
  'startDate' : [] | [Timestamp],
}
export interface GetRetentionPoliciesRequest { 'orgId' : [] | [OrgId] }
export interface GroupAdminRecord {
  'id' : ConversationId,
  'status' : GroupStatus,
  'orgId' : [] | [OrgId],
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'memberCount' : bigint,
}
export type GroupCreationPermission = { 'orgAdminsOnly' : null } |
  { 'allMembers' : null };
export interface GroupMemberRecord {
  'displayName' : [] | [string],
  'userId' : UserId,
  'joinedAt' : Timestamp,
}
export interface GroupRetentionPolicy {
  'retentionEnabled' : boolean,
  'enabledAt' : [] | [Timestamp],
  'enabledBy' : [] | [UserId],
  'convId' : ConversationId,
}
export type GroupStatus = { 'active' : null } |
  { 'suspended' : null };
export interface InviteUserRequest {
  'orgId' : OrgId,
  'role' : OrgRole,
  'email' : [] | [string],
  'principalId' : string,
}
export interface JoinRequest {
  'status' : JoinRequestStatus,
  'requestId' : string,
  'createdAt' : Timestamp,
  'conversationId' : ConversationId,
  'message' : [] | [string],
  'requesterId' : UserId,
}
export interface JoinRequestActionRequest {
  'denialReason' : [] | [DenialReason],
  'requestId' : string,
  'conversationId' : ConversationId,
}
export type JoinRequestStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export interface LegalHoldRequest {
  'orgId' : OrgId,
  'hold' : boolean,
  'reason' : string,
}
export interface ListPublicGroupsRequest {
  'offset' : bigint,
  'limit' : bigint,
  'category' : [] | [string],
}
export type MemberStatus = { 'Active' : null } |
  { 'Suspended' : null } |
  { 'Pending' : null };
export type MessageId = bigint;
export type MessagePriority = { 'normal' : null } |
  { 'high' : null };
export interface MessagePublic {
  'id' : MessageId,
  'ttlSeconds' : [] | [bigint],
  'encryptedContent' : Uint8Array,
  'isDeleted' : boolean,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'messageType' : MessageType,
  'conversationId' : ConversationId,
  'priority' : [] | [MessagePriority],
  'readBy' : Array<ReadReceipt>,
}
export type MessageType = { 'audio' : null } |
  { 'video' : null } |
  { 'file' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface NotificationPreferences {
  'groupMessagesEnabled' : boolean,
  'directMessagesEnabled' : boolean,
}
export type OrgId = string;
export interface OrgMembership {
  'status' : MemberStatus,
  'orgId' : OrgId,
  'userId' : UserId,
  'joinedAt' : Timestamp,
  'role' : OrgRole,
  'invitedBy' : UserId,
  'email' : [] | [string],
  'lastActive' : [] | [Timestamp],
}
export interface OrgRecord {
  'id' : OrgId,
  'status' : OrgStatus,
  'name' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'memberCount' : bigint,
  'description' : string,
}
export type OrgRole = { 'OrgAdmin' : null } |
  { 'Auditor' : null } |
  { 'SuperAdmin' : null } |
  { 'StandardUser' : null };
export interface OrgSettings {
  'legalHoldReason' : [] | [string],
  'orgId' : string,
  'logoStorageKey' : [] | [string],
  'groupCreationPermission' : GroupCreationPermission,
  'dataExportPermission' : DataExportPermission,
  'defaultInviteRole' : string,
  'logoUrl' : [] | [string],
  'legalHoldEnabled' : boolean,
  'messageRetentionDays' : [] | [RetentionPeriodDays],
}
export type OrgStatus = { 'Active' : null } |
  { 'Suspended' : null } |
  { 'Archived' : null };
export type PasswordPolicy = { 'strong' : null } |
  { 'enterprise' : null } |
  { 'basic' : null };
export interface PendingNotification {
  'id' : string,
  'notifType' : string,
  'senderDisplayName' : string,
  'timestamp' : bigint,
  'groupName' : [] | [string],
}
export interface PlatformSettings {
  'defaultRetentionDays' : RetentionPeriodDays,
  'keyEscrowEnabled' : boolean,
  'vetKeysEnabled' : boolean,
  'sessionTimeoutMinutes' : bigint,
  'platformTagline' : string,
  'auditLogRetentionDays' : RetentionPeriodDays,
  'mfaEnforced' : boolean,
  'passwordPolicy' : PasswordPolicy,
  'platformName' : string,
}
export interface PublicGroupSummary {
  'id' : ConversationId,
  'name' : string,
  'memberCount' : bigint,
  'description' : [] | [string],
  'category' : [] | [string],
}
export interface ReadReceipt { 'userId' : UserId, 'readAt' : Timestamp }
export interface RecoveryRequest {
  'id' : bigint,
  'status' : RecoveryRequestStatus,
  'orgId' : [] | [OrgId],
  'approvedBy' : [] | [UserId],
  'createdAt' : Timestamp,
  'initiatingAdmin' : UserId,
  'targetDeviceId' : string,
  'resolvedAt' : [] | [Timestamp],
  'reason' : string,
  'targetUserId' : UserId,
}
export type RecoveryRequestStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface RegisterAttachmentRequest {
  'messageId' : MessageId,
  'mimeType' : string,
  'encryptedSizeBytes' : bigint,
  'storageKey' : string,
}
export interface RegisterRequest {
  'ecdhPublicKey' : EcdhPublicKey,
  'encryptedAvatarKey' : [] | [string],
  'encryptedDisplayName' : Uint8Array,
}
export interface RemoveMemberFromGroupRequest {
  'memberId' : UserId,
  'groupId' : ConversationId,
}
export interface RemoveMemberRequest {
  'member' : UserId,
  'conversationId' : ConversationId,
}
export type Result = { 'ok' : UserProfilePublic } |
  { 'err' : Error };
export type Result_1 = { 'ok' : RetentionPolicy } |
  { 'err' : string };
export type Result_10 = { 'ok' : Attachment } |
  { 'err' : Error };
export type Result_11 = { 'ok' : DeviceRecordPublic } |
  { 'err' : Error };
export type Result_12 = { 'ok' : GetOrgsResponse } |
  { 'err' : string };
export type Result_13 = { 'ok' : Array<UserId> } |
  { 'err' : Error };
export type Result_14 = { 'ok' : OrgMembership } |
  { 'err' : string };
export type Result_15 = { 'ok' : Array<RetentionMetadataRecord> } |
  { 'err' : Error };
export type Result_16 = { 'ok' : Array<RecoveryRequest> } |
  { 'err' : Error };
export type Result_17 = { 'ok' : GetOrgUsersResponse } |
  { 'err' : string };
export type Result_18 = { 'ok' : [] | [OrgRole] } |
  { 'err' : string };
export type Result_19 = { 'ok' : Array<OrgMembership> } |
  { 'err' : string };
export type Result_2 = { 'ok' : null } |
  { 'err' : string };
export type Result_20 = { 'ok' : Array<MessagePublic> } |
  { 'err' : Error };
export type Result_21 = { 'ok' : GroupRetentionPolicy } |
  { 'err' : Error };
export type Result_22 = { 'ok' : Array<GroupMemberRecord> } |
  { 'err' : string };
export type Result_23 = { 'ok' : Array<JoinRequest> } |
  { 'err' : Error };
export type Result_24 = { 'ok' : Array<EscrowedUserRecord> } |
  { 'err' : Error };
export type Result_25 = { 'ok' : EscrowStatsRecord } |
  { 'err' : Error };
export type Result_26 = { 'ok' : Array<AuditEvent> } |
  { 'err' : Error };
export type Result_27 = { 'ok' : string } |
  { 'err' : Error };
export type Result_28 = { 'ok' : ConfigExportBundle } |
  { 'err' : Error };
export type Result_29 = { 'ok' : ConversationPublic } |
  { 'err' : Error };
export type Result_3 = { 'ok' : OrgRecord } |
  { 'err' : string };
export type Result_30 = { 'ok' : EscrowAccessGrant } |
  { 'err' : Error };
export type Result_31 = { 'ok' : Array<EscrowAccessGrant> } |
  { 'err' : Error };
export type Result_4 = { 'ok' : JoinRequest } |
  { 'err' : Error };
export type Result_5 = { 'ok' : SovereignConfig } |
  { 'err' : Error };
export type Result_6 = { 'ok' : null } |
  { 'err' : Error };
export type Result_7 = { 'ok' : MessagePublic } |
  { 'err' : Error };
export type Result_8 = { 'ok' : string } |
  { 'err' : string };
export type Result_9 = { 'ok' : RecoveryRequest } |
  { 'err' : Error };
export interface RetentionMetadataRecord {
  'messageId' : MessageId,
  'sentAt' : Timestamp,
  'senderPrincipal' : UserId,
  'recipientPrincipals' : Array<UserId>,
  'convId' : ConversationId,
}
export type RetentionPeriod = { 'days30' : null } |
  { 'days90' : null } |
  { 'unlimited' : null } |
  { 'years7' : null } |
  { 'year1' : null };
export type RetentionPeriodDays = { 'days30' : null } |
  { 'days90' : null } |
  { 'unlimited' : null } |
  { 'years7' : null } |
  { 'year1' : null };
export interface RetentionPolicy {
  'id' : string,
  'orgId' : [] | [OrgId],
  'period' : RetentionPeriod,
  'legalHold' : boolean,
  'updatedAt' : Timestamp,
  'updatedBy' : UserId,
  'autoDelete' : boolean,
}
export interface SendMessageRequest {
  'ttlSeconds' : [] | [bigint],
  'encryptedContent' : Uint8Array,
  'messageType' : MessageType,
  'conversationId' : ConversationId,
  'priority' : [] | [MessagePriority],
}
export interface SovereignConfig {
  'lastUpdated' : Timestamp,
  'subnetPrincipal' : [] | [Principal],
  'canisters' : string,
  'nodeCount' : [] | [bigint],
  'cyclesCostMultiplier' : [] | [number],
  'residencyLabel' : DataResidency,
}
export interface SubmitJoinRequestRequest {
  'conversationId' : ConversationId,
  'message' : [] | [string],
}
export interface SuspendUserRequest {
  'orgId' : OrgId,
  'userId' : UserId,
  'reason' : string,
}
export type Timestamp = bigint;
export interface TypingIndicatorPublic {
  'expiresAt' : Timestamp,
  'userId' : UserId,
  'conversationId' : ConversationId,
}
export interface UpdateMemberRoleRequest {
  'orgId' : OrgId,
  'userId' : UserId,
  'newRole' : OrgRole,
}
export interface UpdateProfileRequest {
  'ecdhPublicKey' : [] | [EcdhPublicKey],
  'encryptedAvatarKey' : [] | [string],
  'encryptedDisplayName' : [] | [Uint8Array],
}
export interface UpdateRetentionPolicyRequest {
  'id' : string,
  'period' : [] | [RetentionPeriod],
  'legalHold' : [] | [boolean],
  'autoDelete' : [] | [boolean],
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'ecdhPublicKey' : EcdhPublicKey,
  'encryptedAvatarKey' : [] | [string],
  'encryptedDisplayName' : Uint8Array,
  'registeredAt' : Timestamp,
  'lastSeen' : Timestamp,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAdmin' : ActorMethod<[UserId], Result_6>,
  'addConversationMember' : ActorMethod<[AddMemberRequest], Result_6>,
  'addDevice' : ActorMethod<[AddDeviceRequest], Result_11>,
  'adminGetEscrowGrants' : ActorMethod<
    [[] | [UserId], bigint, [] | [bigint]],
    Result_31
  >,
  'adminGrantEscrowAccess' : ActorMethod<[UserId, string, string], Result_30>,
  'approveJoinRequest' : ActorMethod<[JoinRequestActionRequest], Result_6>,
  'approveKeyRecovery' : ActorMethod<[bigint], Result_9>,
  'bootstrapSuperAdmin' : ActorMethod<[UserId], Result_8>,
  'checkPolicyExpiry' : ActorMethod<[[] | [OrgId]], Array<RetentionPolicy>>,
  'clearTypingIndicator' : ActorMethod<[ConversationId], undefined>,
  'createDirectConversation' : ActorMethod<[CreateDirectRequest], Result_29>,
  'createGroupConversation' : ActorMethod<[CreateGroupRequest], Result_29>,
  'createOrg' : ActorMethod<[CreateOrgRequest], Result_3>,
  'createRetentionPolicy' : ActorMethod<
    [CreateRetentionPolicyRequest],
    Result_1
  >,
  'deleteAttachment' : ActorMethod<[AttachmentId], Result_6>,
  'deleteConversation' : ActorMethod<[ConversationId], Result_6>,
  'deleteGroupConversation' : ActorMethod<[ConversationId], Result_6>,
  'deleteOrg' : ActorMethod<[OrgId], Result_2>,
  'denyJoinRequest' : ActorMethod<[JoinRequestActionRequest], Result_6>,
  'disableGroupRetention' : ActorMethod<[ConversationId], Result_6>,
  'enableGroupRetention' : ActorMethod<[ConversationId], Result_6>,
  'enrollKeyEscrow' : ActorMethod<
    [string, string, string, Uint8Array, string],
    Result_6
  >,
  'enrollUserKeyEscrow' : ActorMethod<
    [],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'exportAuditLog' : ActorMethod<[AuditExportRequest], Result_27>,
  'exportAuditLogs' : ActorMethod<[ExportAuditLogsRequest], Result_26>,
  'exportConfigBundle' : ActorMethod<[], Result_28>,
  'generateDeviceSyncToken' : ActorMethod<[Uint8Array], Result_27>,
  'getAllGroups' : ActorMethod<[GetAllGroupsRequest], Array<GroupAdminRecord>>,
  'getAuditLog' : ActorMethod<[GetAuditLogRequest], Result_26>,
  'getCanisterHealth' : ActorMethod<
    [],
    {
      'memoryCapacity' : bigint,
      'cyclesBalance' : bigint,
      'memoryUsed' : bigint,
    }
  >,
  'getConversation' : ActorMethod<[ConversationId], [] | [ConversationPublic]>,
  'getDeploymentInfo' : ActorMethod<[], SovereignConfig>,
  'getEncryptedEscrowKey' : ActorMethod<
    [UserId, Uint8Array],
    { 'ok' : Uint8Array } |
      { 'err' : string }
  >,
  'getEscrowPublicKey' : ActorMethod<
    [],
    { 'ok' : Uint8Array } |
      { 'err' : string }
  >,
  'getEscrowStats' : ActorMethod<[], Result_25>,
  'getEscrowedUsers' : ActorMethod<[GetEscrowedUsersRequest], Result_24>,
  'getGlobalRetentionPolicy' : ActorMethod<[], [] | [RetentionPolicy]>,
  'getGroupCompartment' : ActorMethod<
    [ConversationId],
    [] | [CompartmentLabel]
  >,
  'getGroupJoinRequests' : ActorMethod<[ConversationId], Result_23>,
  'getGroupMembers' : ActorMethod<[GetGroupMembersRequest], Result_22>,
  'getGroupRetentionPolicy' : ActorMethod<[ConversationId], Result_21>,
  'getMessageAttachments' : ActorMethod<[MessageId], Array<Attachment>>,
  'getMessages' : ActorMethod<[GetMessagesRequest], Result_20>,
  'getMyEscrowStatus' : ActorMethod<[], Array<EscrowRecord>>,
  'getMyOrgs' : ActorMethod<[], Result_19>,
  'getMyRole' : ActorMethod<[OrgId], Result_18>,
  'getNotificationPreferences' : ActorMethod<[], NotificationPreferences>,
  'getOrg' : ActorMethod<[OrgId], Result_3>,
  'getOrgSettings' : ActorMethod<[string], OrgSettings>,
  'getOrgUsers' : ActorMethod<[GetOrgUsersRequest], Result_17>,
  'getPendingNotifications' : ActorMethod<[], Array<PendingNotification>>,
  'getPlatformSettings' : ActorMethod<[], PlatformSettings>,
  'getRecoveryDetails' : ActorMethod<[bigint], Result_9>,
  'getRecoveryRequests' : ActorMethod<
    [[] | [OrgId], [] | [RecoveryRequestStatus]],
    Result_16
  >,
  'getRetentionMetadata' : ActorMethod<
    [GetRetentionMetadataRequest],
    Result_15
  >,
  'getRetentionPolicies' : ActorMethod<
    [GetRetentionPoliciesRequest],
    Array<RetentionPolicy>
  >,
  'getRetentionPolicy' : ActorMethod<[OrgId], [] | [RetentionPolicy]>,
  'getTypingIndicators' : ActorMethod<
    [ConversationId],
    Array<TypingIndicatorPublic>
  >,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'getUserProfiles' : ActorMethod<[Array<UserId>], Array<UserProfilePublic>>,
  'getVAPIDPublicKey' : ActorMethod<[], string>,
  'hasDataResetBeenPerformed' : ActorMethod<[], boolean>,
  'hasSuperAdmin' : ActorMethod<[], boolean>,
  'initiateKeyRecovery' : ActorMethod<
    [UserId, string, string, [] | [OrgId]],
    Result_9
  >,
  'inviteUser' : ActorMethod<[InviteUserRequest], Result_14>,
  'isAdminCheck' : ActorMethod<[UserId], boolean>,
  'listAdmins' : ActorMethod<[], Result_13>,
  'listConversations' : ActorMethod<[], Array<ConversationPublic>>,
  'listMyDevices' : ActorMethod<[], Array<DeviceRecordPublic>>,
  'listOrgs' : ActorMethod<[GetOrgsRequest], Result_12>,
  'listPublicGroups' : ActorMethod<
    [ListPublicGroupsRequest],
    Array<PublicGroupSummary>
  >,
  'logPolicyExpiryCheck' : ActorMethod<[], undefined>,
  'logPolicyReportExported' : ActorMethod<[[] | [OrgId]], undefined>,
  'markMessageRead' : ActorMethod<[MessageId], Result_6>,
  'reactivateMember' : ActorMethod<[OrgId, UserId], Result_2>,
  'redeemDeviceSyncToken' : ActorMethod<[string, string, string], Result_11>,
  'registerAttachment' : ActorMethod<[RegisterAttachmentRequest], Result_10>,
  'registerPushSubscription' : ActorMethod<[string, string, string], Result_2>,
  'registerUser' : ActorMethod<[RegisterRequest], Result>,
  'rejectKeyRecovery' : ActorMethod<[bigint], Result_9>,
  'removeAdmin' : ActorMethod<[UserId], Result_6>,
  'removeConversationMember' : ActorMethod<[RemoveMemberRequest], Result_6>,
  'removeMember' : ActorMethod<[OrgId, UserId], Result_2>,
  'removeMemberFromGroup' : ActorMethod<
    [RemoveMemberFromGroupRequest],
    Result_2
  >,
  'resetAllTestData' : ActorMethod<[], Result_8>,
  'revokeDevice' : ActorMethod<[string], Result_6>,
  'revokeKeyEscrow' : ActorMethod<[string, string], Result_6>,
  'sendMessage' : ActorMethod<[SendMessageRequest], Result_7>,
  'sendPushToUser' : ActorMethod<
    [Principal, string, string, string],
    undefined
  >,
  'setGroupCompartment' : ActorMethod<
    [ConversationId, CompartmentLabel],
    Result_6
  >,
  'setSovereignConfig' : ActorMethod<
    [DataResidency, [] | [Principal], [] | [bigint], [] | [number]],
    Result_5
  >,
  'setTypingIndicator' : ActorMethod<[ConversationId, bigint], undefined>,
  'submitJoinRequest' : ActorMethod<[SubmitJoinRequestRequest], Result_4>,
  'subscribeToPush' : ActorMethod<[string, string, string], undefined>,
  'suspendMember' : ActorMethod<[SuspendUserRequest], Result_2>,
  'suspendOrg' : ActorMethod<[OrgId], Result_2>,
  'toggleLegalHold' : ActorMethod<[LegalHoldRequest], Result_1>,
  'touchPresence' : ActorMethod<[], undefined>,
  'unregisterPushSubscription' : ActorMethod<[], Result_2>,
  'unsubscribeFromPush' : ActorMethod<[], undefined>,
  'updateMemberRole' : ActorMethod<[UpdateMemberRoleRequest], Result_2>,
  'updateNotificationPreferences' : ActorMethod<[boolean, boolean], undefined>,
  'updateOrg' : ActorMethod<[OrgId, string, [] | [string]], Result_3>,
  'updateOrgSettings' : ActorMethod<[string, OrgSettings], Result_2>,
  'updatePlatformSettings' : ActorMethod<[PlatformSettings], Result_2>,
  'updateRetentionPolicy' : ActorMethod<
    [UpdateRetentionPolicyRequest],
    Result_1
  >,
  'updateUserProfile' : ActorMethod<[UpdateProfileRequest], Result>,
  'uploadFile' : ActorMethod<[Uint8Array, string], Uint8Array>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];