/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddDeviceRequest {
  'publicKey' : Uint8Array,
  'deviceLabel' : string,
  'deviceId' : string,
}
export interface AddMemberRequest {
  'member' : UserId,
  'conversationId' : ConversationId,
}
export interface Attachment {
  'id' : AttachmentId,
  'messageId' : MessageId,
  'mimeType' : string,
  'encryptedSizeBytes' : bigint,
  'storageKey' : string,
  'uploader' : UserId,
  'uploadedAt' : Timestamp,
}
export type AttachmentId = bigint;
export interface AuditEvent {
  'id' : bigint,
  'targetPrincipal' : [] | [UserId],
  'encryptedDetails' : [] | [Uint8Array],
  'timestamp' : Timestamp,
  'actorPrincipal' : UserId,
  'eventType' : AuditEventType,
}
export type AuditEventType = { 'retentionEnabled' : null } |
  { 'memberAdded' : null } |
  { 'retentionDisabled' : null } |
  { 'escrowAccessGranted' : null } |
  { 'callInitiated' : null } |
  { 'sovereignConfigUpdated' : null } |
  { 'messageQueueDrained' : null } |
  { 'adminAction' : null } |
  { 'auditLogExported' : null } |
  { 'escrowEnrolled' : null } |
  { 'messageSent' : null } |
  { 'escrowRevoked' : null } |
  { 'compartmentAssigned' : null } |
  { 'userRegistered' : null } |
  { 'memberRemoved' : null } |
  { 'userRemoved' : null } |
  { 'priorityMessageSent' : null };
export type AuditExportEventType = { 'retentionEnabled' : null } |
  { 'memberAdded' : null } |
  { 'retentionDisabled' : null } |
  { 'escrowAccessGranted' : null } |
  { 'callInitiated' : null } |
  { 'adminAction' : null } |
  { 'auditLogExported' : null } |
  { 'escrowEnrolled' : null } |
  { 'messageSent' : null } |
  { 'escrowRevoked' : null } |
  { 'userRegistered' : null } |
  { 'memberRemoved' : null } |
  { 'userRemoved' : null };
export type AuditExportFormat = { 'csv' : null } |
  { 'json' : null };
export interface AuditExportRequest {
  'endDate' : [] | [Timestamp],
  'affectedUser' : [] | [UserId],
  'eventTypes' : [] | [Array<AuditExportEventType>],
  'startDate' : [] | [Timestamp],
  'format' : AuditExportFormat,
}
export type CompartmentLabel = { 'classified' : null } |
  { 'unclassified' : null };
export interface ConfigExportBundle {
  'compartmentMappings' : Array<[ConversationId, CompartmentLabel]>,
  'adminPrincipals' : Array<UserId>,
  'exportedAt' : Timestamp,
  'exportedBy' : UserId,
  'subnetPrincipal' : [] | [string],
  'canisters' : string,
  'groupRetentionPolicies' : Array<[ConversationId, GroupRetentionPolicy]>,
  'residencyLabel' : DataResidency,
}
export type ConversationId = bigint;
export type ConversationKind = { 'group' : null } |
  { 'direct' : null };
export interface ConversationPublic {
  'id' : ConversationId,
  'members' : Array<UserId>,
  'lastMessageAt' : Timestamp,
  'displayName' : [] | [string],
  'kind' : ConversationKind,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : [] | [string],
  'category' : [] | [string],
  'discoverable' : boolean,
  'encryptedName' : [] | [Uint8Array],
}
export interface CreateDirectRequest { 'peer' : UserId }
export interface CreateGroupRequest {
  'initialMembers' : Array<UserId>,
  'displayName' : [] | [string],
  'description' : [] | [string],
  'category' : [] | [string],
  'discoverable' : boolean,
  'encryptedName' : Uint8Array,
}
export type DataResidency = { 'eu' : null } |
  { 'us' : null } |
  { 'apac' : null } |
  { 'global' : null };
export type DenialReason = string;
export interface DeviceRecordPublic {
  'publicKey' : Uint8Array,
  'deviceLabel' : string,
  'deviceId' : string,
  'registeredAt' : Timestamp,
  'lastSeen' : Timestamp,
}
export type EcdhPublicKey = Uint8Array;
export type Error = { 'forbidden' : null } |
  { 'alreadyExists' : null } |
  { 'invalidInput' : null } |
  { 'notFound' : null } |
  { 'unauthorized' : null };
export interface EscrowAccessGrant {
  'grantTimestamp' : Timestamp,
  'grantId' : bigint,
  'accessOutcome' : string,
  'targetDeviceId' : string,
  'reason' : string,
  'requestingAdmin' : UserId,
  'targetUserId' : UserId,
}
export interface EscrowRecord {
  'devicePublicKeyFingerprint' : string,
  'userId' : UserId,
  'consentTimestamp' : Timestamp,
  'deviceLabel' : string,
  'wrappedKey' : Uint8Array,
  'deviceId' : string,
  'consentLanguageVersion' : string,
  'revokedAt' : [] | [Timestamp],
  'revokedReason' : [] | [string],
}
export interface GetAuditLogRequest {
  'limit' : bigint,
  'filterEventType' : [] | [AuditEventType],
  'afterEventId' : [] | [bigint],
}
export interface GetMessagesRequest {
  'beforeMessageId' : [] | [MessageId],
  'limit' : bigint,
  'conversationId' : ConversationId,
}
export interface GetRetentionMetadataRequest {
  'endDate' : [] | [Timestamp],
  'limit' : bigint,
  'afterMessageId' : [] | [MessageId],
  'convId' : [] | [ConversationId],
  'startDate' : [] | [Timestamp],
}
export interface GroupRetentionPolicy {
  'retentionEnabled' : boolean,
  'enabledAt' : [] | [Timestamp],
  'enabledBy' : [] | [UserId],
  'convId' : ConversationId,
}
export interface JoinRequest {
  'status' : JoinRequestStatus,
  'requestId' : string,
  'createdAt' : Timestamp,
  'conversationId' : ConversationId,
  'message' : [] | [string],
  'requesterId' : UserId,
}
export interface JoinRequestActionRequest {
  'denialReason' : [] | [DenialReason],
  'requestId' : string,
  'conversationId' : ConversationId,
}
export type JoinRequestStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export interface ListPublicGroupsRequest {
  'offset' : bigint,
  'limit' : bigint,
  'category' : [] | [string],
}
export type MessageId = bigint;
export type MessagePriority = { 'normal' : null } |
  { 'high' : null };
export interface MessagePublic {
  'id' : MessageId,
  'ttlSeconds' : [] | [bigint],
  'encryptedContent' : Uint8Array,
  'isDeleted' : boolean,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'messageType' : MessageType,
  'conversationId' : ConversationId,
  'priority' : [] | [MessagePriority],
  'readBy' : Array<ReadReceipt>,
}
export type MessageType = { 'audio' : null } |
  { 'video' : null } |
  { 'file' : null } |
  { 'text' : null } |
  { 'image' : null };
export interface PublicGroupSummary {
  'id' : ConversationId,
  'name' : string,
  'memberCount' : bigint,
  'description' : [] | [string],
  'category' : [] | [string],
}
export interface ReadReceipt { 'userId' : UserId, 'readAt' : Timestamp }
export interface RegisterAttachmentRequest {
  'messageId' : MessageId,
  'mimeType' : string,
  'encryptedSizeBytes' : bigint,
  'storageKey' : string,
}
export interface RegisterRequest {
  'ecdhPublicKey' : EcdhPublicKey,
  'encryptedAvatarKey' : [] | [string],
  'encryptedDisplayName' : Uint8Array,
}
export interface RemoveMemberRequest {
  'member' : UserId,
  'conversationId' : ConversationId,
}
export type Result = { 'ok' : UserProfilePublic } |
  { 'err' : Error };
export type Result_1 = { 'ok' : JoinRequest } |
  { 'err' : Error };
export type Result_10 = { 'ok' : GroupRetentionPolicy } |
  { 'err' : Error };
export type Result_11 = { 'ok' : Array<JoinRequest> } |
  { 'err' : Error };
export type Result_12 = { 'ok' : Array<AuditEvent> } |
  { 'err' : Error };
export type Result_13 = { 'ok' : string } |
  { 'err' : Error };
export type Result_14 = { 'ok' : ConfigExportBundle } |
  { 'err' : Error };
export type Result_15 = { 'ok' : ConversationPublic } |
  { 'err' : Error };
export type Result_16 = { 'ok' : EscrowAccessGrant } |
  { 'err' : Error };
export type Result_17 = { 'ok' : Array<EscrowAccessGrant> } |
  { 'err' : Error };
export type Result_2 = { 'ok' : SovereignConfig } |
  { 'err' : Error };
export type Result_3 = { 'ok' : null } |
  { 'err' : Error };
export type Result_4 = { 'ok' : MessagePublic } |
  { 'err' : Error };
export type Result_5 = { 'ok' : Attachment } |
  { 'err' : Error };
export type Result_6 = { 'ok' : DeviceRecordPublic } |
  { 'err' : Error };
export type Result_7 = { 'ok' : Array<UserId> } |
  { 'err' : Error };
export type Result_8 = { 'ok' : Array<RetentionMetadataRecord> } |
  { 'err' : Error };
export type Result_9 = { 'ok' : Array<MessagePublic> } |
  { 'err' : Error };
export interface RetentionMetadataRecord {
  'messageId' : MessageId,
  'sentAt' : Timestamp,
  'senderPrincipal' : UserId,
  'recipientPrincipals' : Array<UserId>,
  'convId' : ConversationId,
}
export interface SendMessageRequest {
  'ttlSeconds' : [] | [bigint],
  'encryptedContent' : Uint8Array,
  'messageType' : MessageType,
  'conversationId' : ConversationId,
  'priority' : [] | [MessagePriority],
}
export interface SovereignConfig {
  'lastUpdated' : Timestamp,
  'subnetPrincipal' : [] | [Principal],
  'canisters' : string,
  'nodeCount' : [] | [bigint],
  'cyclesCostMultiplier' : [] | [number],
  'residencyLabel' : DataResidency,
}
export interface SubmitJoinRequestRequest {
  'conversationId' : ConversationId,
  'message' : [] | [string],
}
export type Timestamp = bigint;
export interface TypingIndicatorPublic {
  'expiresAt' : Timestamp,
  'userId' : UserId,
  'conversationId' : ConversationId,
}
export interface UpdateProfileRequest {
  'ecdhPublicKey' : [] | [EcdhPublicKey],
  'encryptedAvatarKey' : [] | [string],
  'encryptedDisplayName' : [] | [Uint8Array],
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'ecdhPublicKey' : EcdhPublicKey,
  'encryptedAvatarKey' : [] | [string],
  'encryptedDisplayName' : Uint8Array,
  'registeredAt' : Timestamp,
  'lastSeen' : Timestamp,
}
export interface _SERVICE {
  'addAdmin' : ActorMethod<[UserId], Result_3>,
  'addConversationMember' : ActorMethod<[AddMemberRequest], Result_3>,
  'addDevice' : ActorMethod<[AddDeviceRequest], Result_6>,
  'adminGetEscrowGrants' : ActorMethod<
    [[] | [UserId], bigint, [] | [bigint]],
    Result_17
  >,
  'adminGrantEscrowAccess' : ActorMethod<[UserId, string, string], Result_16>,
  'approveJoinRequest' : ActorMethod<[JoinRequestActionRequest], Result_3>,
  'clearTypingIndicator' : ActorMethod<[ConversationId], undefined>,
  'createDirectConversation' : ActorMethod<[CreateDirectRequest], Result_15>,
  'createGroupConversation' : ActorMethod<[CreateGroupRequest], Result_15>,
  'deleteAttachment' : ActorMethod<[AttachmentId], Result_3>,
  'deleteConversation' : ActorMethod<[ConversationId], Result_3>,
  'deleteGroupConversation' : ActorMethod<[ConversationId], Result_3>,
  'denyJoinRequest' : ActorMethod<[JoinRequestActionRequest], Result_3>,
  'disableGroupRetention' : ActorMethod<[ConversationId], Result_3>,
  'enableGroupRetention' : ActorMethod<[ConversationId], Result_3>,
  'enrollKeyEscrow' : ActorMethod<
    [string, string, string, Uint8Array, string],
    Result_3
  >,
  'exportAuditLog' : ActorMethod<[AuditExportRequest], Result_13>,
  'exportConfigBundle' : ActorMethod<[], Result_14>,
  'generateDeviceSyncToken' : ActorMethod<[Uint8Array], Result_13>,
  'getAuditLog' : ActorMethod<[GetAuditLogRequest], Result_12>,
  'getConversation' : ActorMethod<[ConversationId], [] | [ConversationPublic]>,
  'getDeploymentInfo' : ActorMethod<[], SovereignConfig>,
  'getGroupCompartment' : ActorMethod<
    [ConversationId],
    [] | [CompartmentLabel]
  >,
  'getGroupJoinRequests' : ActorMethod<[ConversationId], Result_11>,
  'getGroupRetentionPolicy' : ActorMethod<[ConversationId], Result_10>,
  'getMessageAttachments' : ActorMethod<[MessageId], Array<Attachment>>,
  'getMessages' : ActorMethod<[GetMessagesRequest], Result_9>,
  'getMyEscrowStatus' : ActorMethod<[], Array<EscrowRecord>>,
  'getRetentionMetadata' : ActorMethod<[GetRetentionMetadataRequest], Result_8>,
  'getTypingIndicators' : ActorMethod<
    [ConversationId],
    Array<TypingIndicatorPublic>
  >,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'getUserProfiles' : ActorMethod<[Array<UserId>], Array<UserProfilePublic>>,
  'isAdminCheck' : ActorMethod<[UserId], boolean>,
  'listAdmins' : ActorMethod<[], Result_7>,
  'listConversations' : ActorMethod<[], Array<ConversationPublic>>,
  'listMyDevices' : ActorMethod<[], Array<DeviceRecordPublic>>,
  'listPublicGroups' : ActorMethod<
    [ListPublicGroupsRequest],
    Array<PublicGroupSummary>
  >,
  'markMessageRead' : ActorMethod<[MessageId], Result_3>,
  'redeemDeviceSyncToken' : ActorMethod<[string, string, string], Result_6>,
  'registerAttachment' : ActorMethod<[RegisterAttachmentRequest], Result_5>,
  'registerUser' : ActorMethod<[RegisterRequest], Result>,
  'removeAdmin' : ActorMethod<[UserId], Result_3>,
  'removeConversationMember' : ActorMethod<[RemoveMemberRequest], Result_3>,
  'revokeDevice' : ActorMethod<[string], Result_3>,
  'revokeKeyEscrow' : ActorMethod<[string, string], Result_3>,
  'sendMessage' : ActorMethod<[SendMessageRequest], Result_4>,
  'setGroupCompartment' : ActorMethod<
    [ConversationId, CompartmentLabel],
    Result_3
  >,
  'setSovereignConfig' : ActorMethod<
    [DataResidency, [] | [Principal], [] | [bigint], [] | [number]],
    Result_2
  >,
  'setTypingIndicator' : ActorMethod<[ConversationId, bigint], undefined>,
  'submitJoinRequest' : ActorMethod<[SubmitJoinRequestRequest], Result_1>,
  'touchPresence' : ActorMethod<[], undefined>,
  'updateUserProfile' : ActorMethod<[UpdateProfileRequest], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];