/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const Error = IDL.Variant({
  'forbidden' : IDL.Null,
  'alreadyExists' : IDL.Null,
  'invalidInput' : IDL.Null,
  'notFound' : IDL.Null,
  'unauthorized' : IDL.Null,
});
export const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ConversationId = IDL.Nat;
export const AddMemberRequest = IDL.Record({
  'member' : UserId,
  'conversationId' : ConversationId,
});
export const AddDeviceRequest = IDL.Record({
  'publicKey' : IDL.Vec(IDL.Nat8),
  'deviceLabel' : IDL.Text,
  'deviceId' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const DeviceRecordPublic = IDL.Record({
  'publicKey' : IDL.Vec(IDL.Nat8),
  'deviceLabel' : IDL.Text,
  'deviceId' : IDL.Text,
  'registeredAt' : Timestamp,
  'lastSeen' : Timestamp,
});
export const Result_6 = IDL.Variant({
  'ok' : DeviceRecordPublic,
  'err' : Error,
});
export const CallId = IDL.Nat;
export const AddIceCandidateRequest = IDL.Record({
  'encryptedIceCandidate' : IDL.Vec(IDL.Nat8),
  'callId' : CallId,
});
export const EscrowAccessGrant = IDL.Record({
  'grantTimestamp' : Timestamp,
  'grantId' : IDL.Nat,
  'accessOutcome' : IDL.Text,
  'targetDeviceId' : IDL.Text,
  'reason' : IDL.Text,
  'requestingAdmin' : UserId,
  'targetUserId' : UserId,
});
export const Result_18 = IDL.Variant({
  'ok' : IDL.Vec(EscrowAccessGrant),
  'err' : Error,
});
export const Result_17 = IDL.Variant({
  'ok' : EscrowAccessGrant,
  'err' : Error,
});
export const AnswerCallRequest = IDL.Record({
  'callId' : CallId,
  'encryptedSdpAnswer' : IDL.Vec(IDL.Nat8),
});
export const CallStatus = IDL.Variant({
  'active' : IDL.Null,
  'ringing' : IDL.Null,
  'missed' : IDL.Null,
  'ended' : IDL.Null,
  'declined' : IDL.Null,
});
export const CallType = IDL.Variant({ 'audio' : IDL.Null, 'video' : IDL.Null });
export const CallRecordPublic = IDL.Record({
  'id' : CallId,
  'status' : CallStatus,
  'encryptedSdpOffer' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'callees' : IDL.Vec(UserId),
  'callType' : CallType,
  'updatedAt' : Timestamp,
  'conversationId' : IDL.Opt(ConversationId),
  'caller' : UserId,
  'encryptedSdpAnswer' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'iceCandidates' : IDL.Vec(IDL.Vec(IDL.Nat8)),
  'initiatedAt' : Timestamp,
});
export const Result_8 = IDL.Variant({ 'ok' : CallRecordPublic, 'err' : Error });
export const DenialReason = IDL.Text;
export const JoinRequestActionRequest = IDL.Record({
  'denialReason' : IDL.Opt(DenialReason),
  'requestId' : IDL.Text,
  'conversationId' : ConversationId,
});
export const CreateDirectRequest = IDL.Record({ 'peer' : UserId });
export const ConversationKind = IDL.Variant({
  'group' : IDL.Null,
  'direct' : IDL.Null,
});
export const ConversationPublic = IDL.Record({
  'id' : ConversationId,
  'members' : IDL.Vec(UserId),
  'lastMessageAt' : Timestamp,
  'displayName' : IDL.Opt(IDL.Text),
  'kind' : ConversationKind,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'discoverable' : IDL.Bool,
  'encryptedName' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const Result_16 = IDL.Variant({
  'ok' : ConversationPublic,
  'err' : Error,
});
export const CreateGroupRequest = IDL.Record({
  'initialMembers' : IDL.Vec(UserId),
  'displayName' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
  'discoverable' : IDL.Bool,
  'encryptedName' : IDL.Vec(IDL.Nat8),
});
export const AttachmentId = IDL.Nat;
export const AuditExportEventType = IDL.Variant({
  'retentionEnabled' : IDL.Null,
  'memberAdded' : IDL.Null,
  'retentionDisabled' : IDL.Null,
  'escrowAccessGranted' : IDL.Null,
  'callInitiated' : IDL.Null,
  'adminAction' : IDL.Null,
  'auditLogExported' : IDL.Null,
  'escrowEnrolled' : IDL.Null,
  'messageSent' : IDL.Null,
  'escrowRevoked' : IDL.Null,
  'userRegistered' : IDL.Null,
  'memberRemoved' : IDL.Null,
  'userRemoved' : IDL.Null,
});
export const AuditExportFormat = IDL.Variant({
  'csv' : IDL.Null,
  'json' : IDL.Null,
});
export const AuditExportRequest = IDL.Record({
  'endDate' : IDL.Opt(Timestamp),
  'affectedUser' : IDL.Opt(UserId),
  'eventTypes' : IDL.Opt(IDL.Vec(AuditExportEventType)),
  'startDate' : IDL.Opt(Timestamp),
  'format' : AuditExportFormat,
});
export const Result_14 = IDL.Variant({ 'ok' : IDL.Text, 'err' : Error });
export const CompartmentLabel = IDL.Variant({
  'classified' : IDL.Null,
  'unclassified' : IDL.Null,
});
export const GroupRetentionPolicy = IDL.Record({
  'retentionEnabled' : IDL.Bool,
  'enabledAt' : IDL.Opt(Timestamp),
  'enabledBy' : IDL.Opt(UserId),
  'convId' : ConversationId,
});
export const DataResidency = IDL.Variant({
  'eu' : IDL.Null,
  'us' : IDL.Null,
  'apac' : IDL.Null,
  'global' : IDL.Null,
});
export const ConfigExportBundle = IDL.Record({
  'compartmentMappings' : IDL.Vec(IDL.Tuple(ConversationId, CompartmentLabel)),
  'adminPrincipals' : IDL.Vec(UserId),
  'exportedAt' : Timestamp,
  'exportedBy' : UserId,
  'subnetPrincipal' : IDL.Opt(IDL.Text),
  'canisters' : IDL.Text,
  'groupRetentionPolicies' : IDL.Vec(
    IDL.Tuple(ConversationId, GroupRetentionPolicy)
  ),
  'residencyLabel' : DataResidency,
});
export const Result_15 = IDL.Variant({
  'ok' : ConfigExportBundle,
  'err' : Error,
});
export const AuditEventType = IDL.Variant({
  'retentionEnabled' : IDL.Null,
  'memberAdded' : IDL.Null,
  'retentionDisabled' : IDL.Null,
  'escrowAccessGranted' : IDL.Null,
  'callInitiated' : IDL.Null,
  'sovereignConfigUpdated' : IDL.Null,
  'messageQueueDrained' : IDL.Null,
  'adminAction' : IDL.Null,
  'auditLogExported' : IDL.Null,
  'escrowEnrolled' : IDL.Null,
  'messageSent' : IDL.Null,
  'escrowRevoked' : IDL.Null,
  'compartmentAssigned' : IDL.Null,
  'userRegistered' : IDL.Null,
  'memberRemoved' : IDL.Null,
  'userRemoved' : IDL.Null,
  'priorityMessageSent' : IDL.Null,
});
export const GetAuditLogRequest = IDL.Record({
  'limit' : IDL.Nat,
  'filterEventType' : IDL.Opt(AuditEventType),
  'afterEventId' : IDL.Opt(IDL.Nat),
});
export const AuditEvent = IDL.Record({
  'id' : IDL.Nat,
  'targetPrincipal' : IDL.Opt(UserId),
  'encryptedDetails' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'timestamp' : Timestamp,
  'actorPrincipal' : UserId,
  'eventType' : AuditEventType,
});
export const Result_13 = IDL.Variant({
  'ok' : IDL.Vec(AuditEvent),
  'err' : Error,
});
export const SovereignConfig = IDL.Record({
  'lastUpdated' : Timestamp,
  'subnetPrincipal' : IDL.Opt(IDL.Principal),
  'canisters' : IDL.Text,
  'nodeCount' : IDL.Opt(IDL.Nat),
  'cyclesCostMultiplier' : IDL.Opt(IDL.Float64),
  'residencyLabel' : DataResidency,
});
export const JoinRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const JoinRequest = IDL.Record({
  'status' : JoinRequestStatus,
  'requestId' : IDL.Text,
  'createdAt' : Timestamp,
  'conversationId' : ConversationId,
  'message' : IDL.Opt(IDL.Text),
  'requesterId' : UserId,
});
export const Result_12 = IDL.Variant({
  'ok' : IDL.Vec(JoinRequest),
  'err' : Error,
});
export const Result_11 = IDL.Variant({
  'ok' : GroupRetentionPolicy,
  'err' : Error,
});
export const MessageId = IDL.Nat;
export const Attachment = IDL.Record({
  'id' : AttachmentId,
  'messageId' : MessageId,
  'mimeType' : IDL.Text,
  'encryptedSizeBytes' : IDL.Nat,
  'storageKey' : IDL.Text,
  'uploader' : UserId,
  'uploadedAt' : Timestamp,
});
export const GetMessagesRequest = IDL.Record({
  'beforeMessageId' : IDL.Opt(MessageId),
  'limit' : IDL.Nat,
  'conversationId' : ConversationId,
});
export const MessageType = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'file' : IDL.Null,
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const MessagePriority = IDL.Variant({
  'normal' : IDL.Null,
  'high' : IDL.Null,
});
export const ReadReceipt = IDL.Record({
  'userId' : UserId,
  'readAt' : Timestamp,
});
export const MessagePublic = IDL.Record({
  'id' : MessageId,
  'ttlSeconds' : IDL.Opt(IDL.Nat),
  'encryptedContent' : IDL.Vec(IDL.Nat8),
  'isDeleted' : IDL.Bool,
  'sender' : UserId,
  'sentAt' : Timestamp,
  'messageType' : MessageType,
  'conversationId' : ConversationId,
  'priority' : IDL.Opt(MessagePriority),
  'readBy' : IDL.Vec(ReadReceipt),
});
export const Result_10 = IDL.Variant({
  'ok' : IDL.Vec(MessagePublic),
  'err' : Error,
});
export const EscrowRecord = IDL.Record({
  'devicePublicKeyFingerprint' : IDL.Text,
  'userId' : UserId,
  'consentTimestamp' : Timestamp,
  'deviceLabel' : IDL.Text,
  'wrappedKey' : IDL.Vec(IDL.Nat8),
  'deviceId' : IDL.Text,
  'consentLanguageVersion' : IDL.Text,
  'revokedAt' : IDL.Opt(Timestamp),
  'revokedReason' : IDL.Opt(IDL.Text),
});
export const GetRetentionMetadataRequest = IDL.Record({
  'endDate' : IDL.Opt(Timestamp),
  'limit' : IDL.Nat,
  'afterMessageId' : IDL.Opt(MessageId),
  'convId' : IDL.Opt(ConversationId),
  'startDate' : IDL.Opt(Timestamp),
});
export const RetentionMetadataRecord = IDL.Record({
  'messageId' : MessageId,
  'sentAt' : Timestamp,
  'senderPrincipal' : UserId,
  'recipientPrincipals' : IDL.Vec(UserId),
  'convId' : ConversationId,
});
export const Result_9 = IDL.Variant({
  'ok' : IDL.Vec(RetentionMetadataRecord),
  'err' : Error,
});
export const TypingIndicatorPublic = IDL.Record({
  'expiresAt' : Timestamp,
  'userId' : UserId,
  'conversationId' : ConversationId,
});
export const EcdhPublicKey = IDL.Vec(IDL.Nat8);
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'ecdhPublicKey' : EcdhPublicKey,
  'encryptedAvatarKey' : IDL.Opt(IDL.Text),
  'encryptedDisplayName' : IDL.Vec(IDL.Nat8),
  'registeredAt' : Timestamp,
  'lastSeen' : Timestamp,
});
export const InitiateCallRequest = IDL.Record({
  'encryptedSdpOffer' : IDL.Vec(IDL.Nat8),
  'callees' : IDL.Vec(UserId),
  'callType' : CallType,
  'conversationId' : IDL.Opt(ConversationId),
});
export const Result_7 = IDL.Variant({ 'ok' : IDL.Vec(UserId), 'err' : Error });
export const ListPublicGroupsRequest = IDL.Record({
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'category' : IDL.Opt(IDL.Text),
});
export const PublicGroupSummary = IDL.Record({
  'id' : ConversationId,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});
export const RegisterAttachmentRequest = IDL.Record({
  'messageId' : MessageId,
  'mimeType' : IDL.Text,
  'encryptedSizeBytes' : IDL.Nat,
  'storageKey' : IDL.Text,
});
export const Result_5 = IDL.Variant({ 'ok' : Attachment, 'err' : Error });
export const RegisterRequest = IDL.Record({
  'ecdhPublicKey' : EcdhPublicKey,
  'encryptedAvatarKey' : IDL.Opt(IDL.Text),
  'encryptedDisplayName' : IDL.Vec(IDL.Nat8),
});
export const Result = IDL.Variant({ 'ok' : UserProfilePublic, 'err' : Error });
export const RemoveMemberRequest = IDL.Record({
  'member' : UserId,
  'conversationId' : ConversationId,
});
export const SendMessageRequest = IDL.Record({
  'ttlSeconds' : IDL.Opt(IDL.Nat),
  'encryptedContent' : IDL.Vec(IDL.Nat8),
  'messageType' : MessageType,
  'conversationId' : ConversationId,
  'priority' : IDL.Opt(MessagePriority),
});
export const Result_4 = IDL.Variant({ 'ok' : MessagePublic, 'err' : Error });
export const Result_2 = IDL.Variant({ 'ok' : SovereignConfig, 'err' : Error });
export const SubmitJoinRequestRequest = IDL.Record({
  'conversationId' : ConversationId,
  'message' : IDL.Opt(IDL.Text),
});
export const Result_1 = IDL.Variant({ 'ok' : JoinRequest, 'err' : Error });
export const UpdateProfileRequest = IDL.Record({
  'ecdhPublicKey' : IDL.Opt(EcdhPublicKey),
  'encryptedAvatarKey' : IDL.Opt(IDL.Text),
  'encryptedDisplayName' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([UserId], [Result_3], []),
  'addConversationMember' : IDL.Func([AddMemberRequest], [Result_3], []),
  'addDevice' : IDL.Func([AddDeviceRequest], [Result_6], []),
  'addIceCandidate' : IDL.Func([AddIceCandidateRequest], [Result_3], []),
  'adminGetEscrowGrants' : IDL.Func(
      [IDL.Opt(UserId), IDL.Nat, IDL.Opt(IDL.Nat)],
      [Result_18],
      ['query'],
    ),
  'adminGrantEscrowAccess' : IDL.Func(
      [UserId, IDL.Text, IDL.Text],
      [Result_17],
      [],
    ),
  'answerCall' : IDL.Func([AnswerCallRequest], [Result_8], []),
  'approveJoinRequest' : IDL.Func([JoinRequestActionRequest], [Result_3], []),
  'clearTypingIndicator' : IDL.Func([ConversationId], [], []),
  'createDirectConversation' : IDL.Func([CreateDirectRequest], [Result_16], []),
  'createGroupConversation' : IDL.Func([CreateGroupRequest], [Result_16], []),
  'declineCall' : IDL.Func([CallId], [Result_3], []),
  'deleteAttachment' : IDL.Func([AttachmentId], [Result_3], []),
  'deleteConversation' : IDL.Func([ConversationId], [Result_3], []),
  'deleteGroupConversation' : IDL.Func([ConversationId], [Result_3], []),
  'denyJoinRequest' : IDL.Func([JoinRequestActionRequest], [Result_3], []),
  'disableGroupRetention' : IDL.Func([ConversationId], [Result_3], []),
  'enableGroupRetention' : IDL.Func([ConversationId], [Result_3], []),
  'endCall' : IDL.Func([CallId, CallStatus], [Result_3], []),
  'enrollKeyEscrow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text],
      [Result_3],
      [],
    ),
  'exportAuditLog' : IDL.Func([AuditExportRequest], [Result_14], []),
  'exportConfigBundle' : IDL.Func([], [Result_15], []),
  'generateDeviceSyncToken' : IDL.Func([IDL.Vec(IDL.Nat8)], [Result_14], []),
  'getAuditLog' : IDL.Func([GetAuditLogRequest], [Result_13], ['query']),
  'getCall' : IDL.Func([CallId], [IDL.Opt(CallRecordPublic)], ['query']),
  'getConversation' : IDL.Func(
      [ConversationId],
      [IDL.Opt(ConversationPublic)],
      ['query'],
    ),
  'getDeploymentInfo' : IDL.Func([], [SovereignConfig], ['query']),
  'getGroupCompartment' : IDL.Func(
      [ConversationId],
      [IDL.Opt(CompartmentLabel)],
      ['query'],
    ),
  'getGroupJoinRequests' : IDL.Func([ConversationId], [Result_12], ['query']),
  'getGroupRetentionPolicy' : IDL.Func(
      [ConversationId],
      [Result_11],
      ['query'],
    ),
  'getMessageAttachments' : IDL.Func(
      [MessageId],
      [IDL.Vec(Attachment)],
      ['query'],
    ),
  'getMessages' : IDL.Func([GetMessagesRequest], [Result_10], ['query']),
  'getMyEscrowStatus' : IDL.Func([], [IDL.Vec(EscrowRecord)], ['query']),
  'getRetentionMetadata' : IDL.Func(
      [GetRetentionMetadataRequest],
      [Result_9],
      ['query'],
    ),
  'getTypingIndicators' : IDL.Func(
      [ConversationId],
      [IDL.Vec(TypingIndicatorPublic)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getUserProfiles' : IDL.Func(
      [IDL.Vec(UserId)],
      [IDL.Vec(UserProfilePublic)],
      ['query'],
    ),
  'initiateCall' : IDL.Func([InitiateCallRequest], [Result_8], []),
  'isAdminCheck' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'listActiveCalls' : IDL.Func([], [IDL.Vec(CallRecordPublic)], ['query']),
  'listAdmins' : IDL.Func([], [Result_7], ['query']),
  'listConversations' : IDL.Func([], [IDL.Vec(ConversationPublic)], ['query']),
  'listMyDevices' : IDL.Func([], [IDL.Vec(DeviceRecordPublic)], ['query']),
  'listPublicGroups' : IDL.Func(
      [ListPublicGroupsRequest],
      [IDL.Vec(PublicGroupSummary)],
      ['query'],
    ),
  'markMessageRead' : IDL.Func([MessageId], [Result_3], []),
  'redeemDeviceSyncToken' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [Result_6],
      [],
    ),
  'registerAttachment' : IDL.Func([RegisterAttachmentRequest], [Result_5], []),
  'registerUser' : IDL.Func([RegisterRequest], [Result], []),
  'removeAdmin' : IDL.Func([UserId], [Result_3], []),
  'removeConversationMember' : IDL.Func([RemoveMemberRequest], [Result_3], []),
  'revokeDevice' : IDL.Func([IDL.Text], [Result_3], []),
  'revokeKeyEscrow' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
  'sendMessage' : IDL.Func([SendMessageRequest], [Result_4], []),
  'setGroupCompartment' : IDL.Func(
      [ConversationId, CompartmentLabel],
      [Result_3],
      [],
    ),
  'setSovereignConfig' : IDL.Func(
      [
        DataResidency,
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Float64),
      ],
      [Result_2],
      [],
    ),
  'setTypingIndicator' : IDL.Func([ConversationId, IDL.Nat], [], []),
  'submitJoinRequest' : IDL.Func([SubmitJoinRequestRequest], [Result_1], []),
  'touchPresence' : IDL.Func([], [], []),
  'updateUserProfile' : IDL.Func([UpdateProfileRequest], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const Error = IDL.Variant({
    'forbidden' : IDL.Null,
    'alreadyExists' : IDL.Null,
    'invalidInput' : IDL.Null,
    'notFound' : IDL.Null,
    'unauthorized' : IDL.Null,
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ConversationId = IDL.Nat;
  const AddMemberRequest = IDL.Record({
    'member' : UserId,
    'conversationId' : ConversationId,
  });
  const AddDeviceRequest = IDL.Record({
    'publicKey' : IDL.Vec(IDL.Nat8),
    'deviceLabel' : IDL.Text,
    'deviceId' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const DeviceRecordPublic = IDL.Record({
    'publicKey' : IDL.Vec(IDL.Nat8),
    'deviceLabel' : IDL.Text,
    'deviceId' : IDL.Text,
    'registeredAt' : Timestamp,
    'lastSeen' : Timestamp,
  });
  const Result_6 = IDL.Variant({ 'ok' : DeviceRecordPublic, 'err' : Error });
  const CallId = IDL.Nat;
  const AddIceCandidateRequest = IDL.Record({
    'encryptedIceCandidate' : IDL.Vec(IDL.Nat8),
    'callId' : CallId,
  });
  const EscrowAccessGrant = IDL.Record({
    'grantTimestamp' : Timestamp,
    'grantId' : IDL.Nat,
    'accessOutcome' : IDL.Text,
    'targetDeviceId' : IDL.Text,
    'reason' : IDL.Text,
    'requestingAdmin' : UserId,
    'targetUserId' : UserId,
  });
  const Result_18 = IDL.Variant({
    'ok' : IDL.Vec(EscrowAccessGrant),
    'err' : Error,
  });
  const Result_17 = IDL.Variant({ 'ok' : EscrowAccessGrant, 'err' : Error });
  const AnswerCallRequest = IDL.Record({
    'callId' : CallId,
    'encryptedSdpAnswer' : IDL.Vec(IDL.Nat8),
  });
  const CallStatus = IDL.Variant({
    'active' : IDL.Null,
    'ringing' : IDL.Null,
    'missed' : IDL.Null,
    'ended' : IDL.Null,
    'declined' : IDL.Null,
  });
  const CallType = IDL.Variant({ 'audio' : IDL.Null, 'video' : IDL.Null });
  const CallRecordPublic = IDL.Record({
    'id' : CallId,
    'status' : CallStatus,
    'encryptedSdpOffer' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'callees' : IDL.Vec(UserId),
    'callType' : CallType,
    'updatedAt' : Timestamp,
    'conversationId' : IDL.Opt(ConversationId),
    'caller' : UserId,
    'encryptedSdpAnswer' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'iceCandidates' : IDL.Vec(IDL.Vec(IDL.Nat8)),
    'initiatedAt' : Timestamp,
  });
  const Result_8 = IDL.Variant({ 'ok' : CallRecordPublic, 'err' : Error });
  const DenialReason = IDL.Text;
  const JoinRequestActionRequest = IDL.Record({
    'denialReason' : IDL.Opt(DenialReason),
    'requestId' : IDL.Text,
    'conversationId' : ConversationId,
  });
  const CreateDirectRequest = IDL.Record({ 'peer' : UserId });
  const ConversationKind = IDL.Variant({
    'group' : IDL.Null,
    'direct' : IDL.Null,
  });
  const ConversationPublic = IDL.Record({
    'id' : ConversationId,
    'members' : IDL.Vec(UserId),
    'lastMessageAt' : Timestamp,
    'displayName' : IDL.Opt(IDL.Text),
    'kind' : ConversationKind,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'discoverable' : IDL.Bool,
    'encryptedName' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const Result_16 = IDL.Variant({ 'ok' : ConversationPublic, 'err' : Error });
  const CreateGroupRequest = IDL.Record({
    'initialMembers' : IDL.Vec(UserId),
    'displayName' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
    'discoverable' : IDL.Bool,
    'encryptedName' : IDL.Vec(IDL.Nat8),
  });
  const AttachmentId = IDL.Nat;
  const AuditExportEventType = IDL.Variant({
    'retentionEnabled' : IDL.Null,
    'memberAdded' : IDL.Null,
    'retentionDisabled' : IDL.Null,
    'escrowAccessGranted' : IDL.Null,
    'callInitiated' : IDL.Null,
    'adminAction' : IDL.Null,
    'auditLogExported' : IDL.Null,
    'escrowEnrolled' : IDL.Null,
    'messageSent' : IDL.Null,
    'escrowRevoked' : IDL.Null,
    'userRegistered' : IDL.Null,
    'memberRemoved' : IDL.Null,
    'userRemoved' : IDL.Null,
  });
  const AuditExportFormat = IDL.Variant({
    'csv' : IDL.Null,
    'json' : IDL.Null,
  });
  const AuditExportRequest = IDL.Record({
    'endDate' : IDL.Opt(Timestamp),
    'affectedUser' : IDL.Opt(UserId),
    'eventTypes' : IDL.Opt(IDL.Vec(AuditExportEventType)),
    'startDate' : IDL.Opt(Timestamp),
    'format' : AuditExportFormat,
  });
  const Result_14 = IDL.Variant({ 'ok' : IDL.Text, 'err' : Error });
  const CompartmentLabel = IDL.Variant({
    'classified' : IDL.Null,
    'unclassified' : IDL.Null,
  });
  const GroupRetentionPolicy = IDL.Record({
    'retentionEnabled' : IDL.Bool,
    'enabledAt' : IDL.Opt(Timestamp),
    'enabledBy' : IDL.Opt(UserId),
    'convId' : ConversationId,
  });
  const DataResidency = IDL.Variant({
    'eu' : IDL.Null,
    'us' : IDL.Null,
    'apac' : IDL.Null,
    'global' : IDL.Null,
  });
  const ConfigExportBundle = IDL.Record({
    'compartmentMappings' : IDL.Vec(
      IDL.Tuple(ConversationId, CompartmentLabel)
    ),
    'adminPrincipals' : IDL.Vec(UserId),
    'exportedAt' : Timestamp,
    'exportedBy' : UserId,
    'subnetPrincipal' : IDL.Opt(IDL.Text),
    'canisters' : IDL.Text,
    'groupRetentionPolicies' : IDL.Vec(
      IDL.Tuple(ConversationId, GroupRetentionPolicy)
    ),
    'residencyLabel' : DataResidency,
  });
  const Result_15 = IDL.Variant({ 'ok' : ConfigExportBundle, 'err' : Error });
  const AuditEventType = IDL.Variant({
    'retentionEnabled' : IDL.Null,
    'memberAdded' : IDL.Null,
    'retentionDisabled' : IDL.Null,
    'escrowAccessGranted' : IDL.Null,
    'callInitiated' : IDL.Null,
    'sovereignConfigUpdated' : IDL.Null,
    'messageQueueDrained' : IDL.Null,
    'adminAction' : IDL.Null,
    'auditLogExported' : IDL.Null,
    'escrowEnrolled' : IDL.Null,
    'messageSent' : IDL.Null,
    'escrowRevoked' : IDL.Null,
    'compartmentAssigned' : IDL.Null,
    'userRegistered' : IDL.Null,
    'memberRemoved' : IDL.Null,
    'userRemoved' : IDL.Null,
    'priorityMessageSent' : IDL.Null,
  });
  const GetAuditLogRequest = IDL.Record({
    'limit' : IDL.Nat,
    'filterEventType' : IDL.Opt(AuditEventType),
    'afterEventId' : IDL.Opt(IDL.Nat),
  });
  const AuditEvent = IDL.Record({
    'id' : IDL.Nat,
    'targetPrincipal' : IDL.Opt(UserId),
    'encryptedDetails' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'timestamp' : Timestamp,
    'actorPrincipal' : UserId,
    'eventType' : AuditEventType,
  });
  const Result_13 = IDL.Variant({ 'ok' : IDL.Vec(AuditEvent), 'err' : Error });
  const SovereignConfig = IDL.Record({
    'lastUpdated' : Timestamp,
    'subnetPrincipal' : IDL.Opt(IDL.Principal),
    'canisters' : IDL.Text,
    'nodeCount' : IDL.Opt(IDL.Nat),
    'cyclesCostMultiplier' : IDL.Opt(IDL.Float64),
    'residencyLabel' : DataResidency,
  });
  const JoinRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const JoinRequest = IDL.Record({
    'status' : JoinRequestStatus,
    'requestId' : IDL.Text,
    'createdAt' : Timestamp,
    'conversationId' : ConversationId,
    'message' : IDL.Opt(IDL.Text),
    'requesterId' : UserId,
  });
  const Result_12 = IDL.Variant({ 'ok' : IDL.Vec(JoinRequest), 'err' : Error });
  const Result_11 = IDL.Variant({ 'ok' : GroupRetentionPolicy, 'err' : Error });
  const MessageId = IDL.Nat;
  const Attachment = IDL.Record({
    'id' : AttachmentId,
    'messageId' : MessageId,
    'mimeType' : IDL.Text,
    'encryptedSizeBytes' : IDL.Nat,
    'storageKey' : IDL.Text,
    'uploader' : UserId,
    'uploadedAt' : Timestamp,
  });
  const GetMessagesRequest = IDL.Record({
    'beforeMessageId' : IDL.Opt(MessageId),
    'limit' : IDL.Nat,
    'conversationId' : ConversationId,
  });
  const MessageType = IDL.Variant({
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'file' : IDL.Null,
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const MessagePriority = IDL.Variant({
    'normal' : IDL.Null,
    'high' : IDL.Null,
  });
  const ReadReceipt = IDL.Record({ 'userId' : UserId, 'readAt' : Timestamp });
  const MessagePublic = IDL.Record({
    'id' : MessageId,
    'ttlSeconds' : IDL.Opt(IDL.Nat),
    'encryptedContent' : IDL.Vec(IDL.Nat8),
    'isDeleted' : IDL.Bool,
    'sender' : UserId,
    'sentAt' : Timestamp,
    'messageType' : MessageType,
    'conversationId' : ConversationId,
    'priority' : IDL.Opt(MessagePriority),
    'readBy' : IDL.Vec(ReadReceipt),
  });
  const Result_10 = IDL.Variant({
    'ok' : IDL.Vec(MessagePublic),
    'err' : Error,
  });
  const EscrowRecord = IDL.Record({
    'devicePublicKeyFingerprint' : IDL.Text,
    'userId' : UserId,
    'consentTimestamp' : Timestamp,
    'deviceLabel' : IDL.Text,
    'wrappedKey' : IDL.Vec(IDL.Nat8),
    'deviceId' : IDL.Text,
    'consentLanguageVersion' : IDL.Text,
    'revokedAt' : IDL.Opt(Timestamp),
    'revokedReason' : IDL.Opt(IDL.Text),
  });
  const GetRetentionMetadataRequest = IDL.Record({
    'endDate' : IDL.Opt(Timestamp),
    'limit' : IDL.Nat,
    'afterMessageId' : IDL.Opt(MessageId),
    'convId' : IDL.Opt(ConversationId),
    'startDate' : IDL.Opt(Timestamp),
  });
  const RetentionMetadataRecord = IDL.Record({
    'messageId' : MessageId,
    'sentAt' : Timestamp,
    'senderPrincipal' : UserId,
    'recipientPrincipals' : IDL.Vec(UserId),
    'convId' : ConversationId,
  });
  const Result_9 = IDL.Variant({
    'ok' : IDL.Vec(RetentionMetadataRecord),
    'err' : Error,
  });
  const TypingIndicatorPublic = IDL.Record({
    'expiresAt' : Timestamp,
    'userId' : UserId,
    'conversationId' : ConversationId,
  });
  const EcdhPublicKey = IDL.Vec(IDL.Nat8);
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'ecdhPublicKey' : EcdhPublicKey,
    'encryptedAvatarKey' : IDL.Opt(IDL.Text),
    'encryptedDisplayName' : IDL.Vec(IDL.Nat8),
    'registeredAt' : Timestamp,
    'lastSeen' : Timestamp,
  });
  const InitiateCallRequest = IDL.Record({
    'encryptedSdpOffer' : IDL.Vec(IDL.Nat8),
    'callees' : IDL.Vec(UserId),
    'callType' : CallType,
    'conversationId' : IDL.Opt(ConversationId),
  });
  const Result_7 = IDL.Variant({ 'ok' : IDL.Vec(UserId), 'err' : Error });
  const ListPublicGroupsRequest = IDL.Record({
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'category' : IDL.Opt(IDL.Text),
  });
  const PublicGroupSummary = IDL.Record({
    'id' : ConversationId,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  const RegisterAttachmentRequest = IDL.Record({
    'messageId' : MessageId,
    'mimeType' : IDL.Text,
    'encryptedSizeBytes' : IDL.Nat,
    'storageKey' : IDL.Text,
  });
  const Result_5 = IDL.Variant({ 'ok' : Attachment, 'err' : Error });
  const RegisterRequest = IDL.Record({
    'ecdhPublicKey' : EcdhPublicKey,
    'encryptedAvatarKey' : IDL.Opt(IDL.Text),
    'encryptedDisplayName' : IDL.Vec(IDL.Nat8),
  });
  const Result = IDL.Variant({ 'ok' : UserProfilePublic, 'err' : Error });
  const RemoveMemberRequest = IDL.Record({
    'member' : UserId,
    'conversationId' : ConversationId,
  });
  const SendMessageRequest = IDL.Record({
    'ttlSeconds' : IDL.Opt(IDL.Nat),
    'encryptedContent' : IDL.Vec(IDL.Nat8),
    'messageType' : MessageType,
    'conversationId' : ConversationId,
    'priority' : IDL.Opt(MessagePriority),
  });
  const Result_4 = IDL.Variant({ 'ok' : MessagePublic, 'err' : Error });
  const Result_2 = IDL.Variant({ 'ok' : SovereignConfig, 'err' : Error });
  const SubmitJoinRequestRequest = IDL.Record({
    'conversationId' : ConversationId,
    'message' : IDL.Opt(IDL.Text),
  });
  const Result_1 = IDL.Variant({ 'ok' : JoinRequest, 'err' : Error });
  const UpdateProfileRequest = IDL.Record({
    'ecdhPublicKey' : IDL.Opt(EcdhPublicKey),
    'encryptedAvatarKey' : IDL.Opt(IDL.Text),
    'encryptedDisplayName' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([UserId], [Result_3], []),
    'addConversationMember' : IDL.Func([AddMemberRequest], [Result_3], []),
    'addDevice' : IDL.Func([AddDeviceRequest], [Result_6], []),
    'addIceCandidate' : IDL.Func([AddIceCandidateRequest], [Result_3], []),
    'adminGetEscrowGrants' : IDL.Func(
        [IDL.Opt(UserId), IDL.Nat, IDL.Opt(IDL.Nat)],
        [Result_18],
        ['query'],
      ),
    'adminGrantEscrowAccess' : IDL.Func(
        [UserId, IDL.Text, IDL.Text],
        [Result_17],
        [],
      ),
    'answerCall' : IDL.Func([AnswerCallRequest], [Result_8], []),
    'approveJoinRequest' : IDL.Func([JoinRequestActionRequest], [Result_3], []),
    'clearTypingIndicator' : IDL.Func([ConversationId], [], []),
    'createDirectConversation' : IDL.Func(
        [CreateDirectRequest],
        [Result_16],
        [],
      ),
    'createGroupConversation' : IDL.Func([CreateGroupRequest], [Result_16], []),
    'declineCall' : IDL.Func([CallId], [Result_3], []),
    'deleteAttachment' : IDL.Func([AttachmentId], [Result_3], []),
    'deleteConversation' : IDL.Func([ConversationId], [Result_3], []),
    'deleteGroupConversation' : IDL.Func([ConversationId], [Result_3], []),
    'denyJoinRequest' : IDL.Func([JoinRequestActionRequest], [Result_3], []),
    'disableGroupRetention' : IDL.Func([ConversationId], [Result_3], []),
    'enableGroupRetention' : IDL.Func([ConversationId], [Result_3], []),
    'endCall' : IDL.Func([CallId, CallStatus], [Result_3], []),
    'enrollKeyEscrow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8), IDL.Text],
        [Result_3],
        [],
      ),
    'exportAuditLog' : IDL.Func([AuditExportRequest], [Result_14], []),
    'exportConfigBundle' : IDL.Func([], [Result_15], []),
    'generateDeviceSyncToken' : IDL.Func([IDL.Vec(IDL.Nat8)], [Result_14], []),
    'getAuditLog' : IDL.Func([GetAuditLogRequest], [Result_13], ['query']),
    'getCall' : IDL.Func([CallId], [IDL.Opt(CallRecordPublic)], ['query']),
    'getConversation' : IDL.Func(
        [ConversationId],
        [IDL.Opt(ConversationPublic)],
        ['query'],
      ),
    'getDeploymentInfo' : IDL.Func([], [SovereignConfig], ['query']),
    'getGroupCompartment' : IDL.Func(
        [ConversationId],
        [IDL.Opt(CompartmentLabel)],
        ['query'],
      ),
    'getGroupJoinRequests' : IDL.Func([ConversationId], [Result_12], ['query']),
    'getGroupRetentionPolicy' : IDL.Func(
        [ConversationId],
        [Result_11],
        ['query'],
      ),
    'getMessageAttachments' : IDL.Func(
        [MessageId],
        [IDL.Vec(Attachment)],
        ['query'],
      ),
    'getMessages' : IDL.Func([GetMessagesRequest], [Result_10], ['query']),
    'getMyEscrowStatus' : IDL.Func([], [IDL.Vec(EscrowRecord)], ['query']),
    'getRetentionMetadata' : IDL.Func(
        [GetRetentionMetadataRequest],
        [Result_9],
        ['query'],
      ),
    'getTypingIndicators' : IDL.Func(
        [ConversationId],
        [IDL.Vec(TypingIndicatorPublic)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getUserProfiles' : IDL.Func(
        [IDL.Vec(UserId)],
        [IDL.Vec(UserProfilePublic)],
        ['query'],
      ),
    'initiateCall' : IDL.Func([InitiateCallRequest], [Result_8], []),
    'isAdminCheck' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'listActiveCalls' : IDL.Func([], [IDL.Vec(CallRecordPublic)], ['query']),
    'listAdmins' : IDL.Func([], [Result_7], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationPublic)],
        ['query'],
      ),
    'listMyDevices' : IDL.Func([], [IDL.Vec(DeviceRecordPublic)], ['query']),
    'listPublicGroups' : IDL.Func(
        [ListPublicGroupsRequest],
        [IDL.Vec(PublicGroupSummary)],
        ['query'],
      ),
    'markMessageRead' : IDL.Func([MessageId], [Result_3], []),
    'redeemDeviceSyncToken' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [Result_6],
        [],
      ),
    'registerAttachment' : IDL.Func(
        [RegisterAttachmentRequest],
        [Result_5],
        [],
      ),
    'registerUser' : IDL.Func([RegisterRequest], [Result], []),
    'removeAdmin' : IDL.Func([UserId], [Result_3], []),
    'removeConversationMember' : IDL.Func(
        [RemoveMemberRequest],
        [Result_3],
        [],
      ),
    'revokeDevice' : IDL.Func([IDL.Text], [Result_3], []),
    'revokeKeyEscrow' : IDL.Func([IDL.Text, IDL.Text], [Result_3], []),
    'sendMessage' : IDL.Func([SendMessageRequest], [Result_4], []),
    'setGroupCompartment' : IDL.Func(
        [ConversationId, CompartmentLabel],
        [Result_3],
        [],
      ),
    'setSovereignConfig' : IDL.Func(
        [
          DataResidency,
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Float64),
        ],
        [Result_2],
        [],
      ),
    'setTypingIndicator' : IDL.Func([ConversationId, IDL.Nat], [], []),
    'submitJoinRequest' : IDL.Func([SubmitJoinRequestRequest], [Result_1], []),
    'touchPresence' : IDL.Func([], [], []),
    'updateUserProfile' : IDL.Func([UpdateProfileRequest], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };